### ISSUE TITLE
Spremeni opis

### ISSUE THREAD

**Issue by KrOstir** [UL-FGG/geo3#2]
Opis ni OK, @novakanja popravi.

**Comment by ArminaKaric** [comment]
Uredu je

**Comment by novakanja** [comment]
Popravljeno.

**Comment by matejv98** [comment]
Hello world

**Comment by matjazkrebs** [comment]
brez napak

**Comment by KrOstir** [comment]
Hkrati rešimo #1 .

![slika](https://user-images.githubusercontent.com/13023733/158224914-c409f044-44e4-40a7-a6b3-dd02513fa9a2.png)

**Comment by blauteri** [comment]
bp

**Comment by KrOstir** [comment]
> Hello

OK

**Comment by GTanja** [comment]
Problem rešen
